#############################################################################
# Makefile for building: qoq
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  qoq.pro
# Template: app
# Command: /home/kakadu/prog/qt/qt_off/5.3/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile qoq.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_QUICK_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../qt_off/5.3/gcc_64/mkspecs/linux-g++ -I. -I../qt_off/5.3/gcc_64/include -I../qt_off/5.3/gcc_64/include/QtQuick -I../qt_off/5.3/gcc_64/include/QtQml -I../qt_off/5.3/gcc_64/include/QtWidgets -I../qt_off/5.3/gcc_64/include/QtNetwork -I../qt_off/5.3/gcc_64/include/QtGui -I../qt_off/5.3/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/kakadu/prog/qt/qt_off/5.3/gcc_64 -Wl,-rpath,/home/kakadu/prog/qt/qt_off/5.3/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/kakadu/prog/qt/qt_off/5.3/gcc_64/lib -lQt5Quick -lQt5Qml -lQt5Widgets -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/kakadu/prog/qt/qt_off/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		documenthandler.cpp \
		highlighter.cpp qrc_qml.cpp \
		moc_documenthandler.cpp \
		moc_highlighter.cpp
OBJECTS       = main.o \
		documenthandler.o \
		highlighter.o \
		qrc_qml.o \
		moc_documenthandler.o \
		moc_highlighter.o
DIST          = ../qt_off/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../qt_off/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../qt_off/5.3/gcc_64/mkspecs/common/unix.conf \
		../qt_off/5.3/gcc_64/mkspecs/common/linux.conf \
		../qt_off/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../qt_off/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../qt_off/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../qt_off/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../qt_off/5.3/gcc_64/mkspecs/qconfig.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../qt_off/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../qt_off/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		../qt_off/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/default_post.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/qml_debug.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/declarative_debug.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/qt.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/resources.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/moc.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/uic.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/yacc.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/lex.prf \
		qoq.pro main.cpp \
		documenthandler.cpp \
		highlighter.cpp
QMAKE_TARGET  = qoq
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = qoq


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qoq.pro ../qt_off/5.3/gcc_64/mkspecs/linux-g++/qmake.conf ../qt_off/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../qt_off/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../qt_off/5.3/gcc_64/mkspecs/common/unix.conf \
		../qt_off/5.3/gcc_64/mkspecs/common/linux.conf \
		../qt_off/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../qt_off/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../qt_off/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../qt_off/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../qt_off/5.3/gcc_64/mkspecs/qconfig.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../qt_off/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../qt_off/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../qt_off/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		../qt_off/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/default_post.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/qml_debug.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/declarative_debug.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/qt.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/resources.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/moc.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/uic.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/yacc.prf \
		../qt_off/5.3/gcc_64/mkspecs/features/lex.prf \
		qoq.pro \
		qml.qrc \
		/home/kakadu/prog/qt/qt_off/5.3/gcc_64/lib/libQt5Quick.prl \
		/home/kakadu/prog/qt/qt_off/5.3/gcc_64/lib/libQt5Qml.prl \
		/home/kakadu/prog/qt/qt_off/5.3/gcc_64/lib/libQt5Network.prl \
		/home/kakadu/prog/qt/qt_off/5.3/gcc_64/lib/libQt5Core.prl \
		/home/kakadu/prog/qt/qt_off/5.3/gcc_64/lib/libQt5Gui.prl \
		/home/kakadu/prog/qt/qt_off/5.3/gcc_64/lib/libQt5Widgets.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile qoq.pro
../qt_off/5.3/gcc_64/mkspecs/features/spec_pre.prf:
../qt_off/5.3/gcc_64/mkspecs/common/shell-unix.conf:
../qt_off/5.3/gcc_64/mkspecs/common/unix.conf:
../qt_off/5.3/gcc_64/mkspecs/common/linux.conf:
../qt_off/5.3/gcc_64/mkspecs/common/gcc-base.conf:
../qt_off/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../qt_off/5.3/gcc_64/mkspecs/common/g++-base.conf:
../qt_off/5.3/gcc_64/mkspecs/common/g++-unix.conf:
../qt_off/5.3/gcc_64/mkspecs/qconfig.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../qt_off/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../qt_off/5.3/gcc_64/mkspecs/features/qt_functions.prf:
../qt_off/5.3/gcc_64/mkspecs/features/qt_config.prf:
../qt_off/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
../qt_off/5.3/gcc_64/mkspecs/features/spec_post.prf:
../qt_off/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../qt_off/5.3/gcc_64/mkspecs/features/default_pre.prf:
deployment.pri:
../qt_off/5.3/gcc_64/mkspecs/features/resolve_config.prf:
../qt_off/5.3/gcc_64/mkspecs/features/default_post.prf:
../qt_off/5.3/gcc_64/mkspecs/features/qml_debug.prf:
../qt_off/5.3/gcc_64/mkspecs/features/declarative_debug.prf:
../qt_off/5.3/gcc_64/mkspecs/features/warn_on.prf:
../qt_off/5.3/gcc_64/mkspecs/features/qt.prf:
../qt_off/5.3/gcc_64/mkspecs/features/resources.prf:
../qt_off/5.3/gcc_64/mkspecs/features/moc.prf:
../qt_off/5.3/gcc_64/mkspecs/features/unix/opengl.prf:
../qt_off/5.3/gcc_64/mkspecs/features/uic.prf:
../qt_off/5.3/gcc_64/mkspecs/features/unix/thread.prf:
../qt_off/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
../qt_off/5.3/gcc_64/mkspecs/features/exceptions.prf:
../qt_off/5.3/gcc_64/mkspecs/features/yacc.prf:
../qt_off/5.3/gcc_64/mkspecs/features/lex.prf:
qoq.pro:
qml.qrc:
/home/kakadu/prog/qt/qt_off/5.3/gcc_64/lib/libQt5Quick.prl:
/home/kakadu/prog/qt/qt_off/5.3/gcc_64/lib/libQt5Qml.prl:
/home/kakadu/prog/qt/qt_off/5.3/gcc_64/lib/libQt5Network.prl:
/home/kakadu/prog/qt/qt_off/5.3/gcc_64/lib/libQt5Core.prl:
/home/kakadu/prog/qt/qt_off/5.3/gcc_64/lib/libQt5Gui.prl:
/home/kakadu/prog/qt/qt_off/5.3/gcc_64/lib/libQt5Widgets.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile qoq.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/qoq1.0.0 || mkdir -p .tmp/qoq1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/qoq1.0.0/ && $(COPY_FILE) --parents qml.qrc .tmp/qoq1.0.0/ && $(COPY_FILE) --parents documenthandler.h highlighter.h .tmp/qoq1.0.0/ && $(COPY_FILE) --parents main.cpp documenthandler.cpp highlighter.cpp .tmp/qoq1.0.0/ && (cd `dirname .tmp/qoq1.0.0` && $(TAR) qoq1.0.0.tar qoq1.0.0 && $(COMPRESS) qoq1.0.0.tar) && $(MOVE) `dirname .tmp/qoq1.0.0`/qoq1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qoq1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		Main.js \
		main.qml
	/home/kakadu/prog/qt/qt_off/5.3/gcc_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_documenthandler.cpp moc_highlighter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_documenthandler.cpp moc_highlighter.cpp
moc_documenthandler.cpp: ../qt_off/5.3/gcc_64/include/QtQuick/QQuickTextDocument \
		../qt_off/5.3/gcc_64/include/QtQuick/qquicktextdocument.h \
		../qt_off/5.3/gcc_64/include/QtGui/QTextDocument \
		../qt_off/5.3/gcc_64/include/QtGui/qtextdocument.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobject.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../qt_off/5.3/gcc_64/include/QtCore/qnamespace.h \
		../qt_off/5.3/gcc_64/include/QtCore/qglobal.h \
		../qt_off/5.3/gcc_64/include/QtCore/qconfig.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfeatures.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlogging.h \
		../qt_off/5.3/gcc_64/include/QtCore/qflags.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../qt_off/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../qt_off/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmutex.h \
		../qt_off/5.3/gcc_64/include/QtCore/qnumeric.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstring.h \
		../qt_off/5.3/gcc_64/include/QtCore/qchar.h \
		../qt_off/5.3/gcc_64/include/QtCore/qbytearray.h \
		../qt_off/5.3/gcc_64/include/QtCore/qrefcount.h \
		../qt_off/5.3/gcc_64/include/QtCore/qarraydata.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlist.h \
		../qt_off/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../qt_off/5.3/gcc_64/include/QtCore/qiterator.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../qt_off/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmetatype.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../qt_off/5.3/gcc_64/include/QtCore/qisenum.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsize.h \
		../qt_off/5.3/gcc_64/include/QtCore/qrect.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmargins.h \
		../qt_off/5.3/gcc_64/include/QtCore/qpoint.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvariant.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmap.h \
		../qt_off/5.3/gcc_64/include/QtCore/qpair.h \
		../qt_off/5.3/gcc_64/include/QtCore/qdebug.h \
		../qt_off/5.3/gcc_64/include/QtCore/qhash.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtextstream.h \
		../qt_off/5.3/gcc_64/include/QtCore/qiodevice.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlocale.h \
		../qt_off/5.3/gcc_64/include/QtCore/qshareddata.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvector.h \
		../qt_off/5.3/gcc_64/include/QtCore/qset.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringlist.h \
		../qt_off/5.3/gcc_64/include/QtCore/qdatastream.h \
		../qt_off/5.3/gcc_64/include/QtCore/qregexp.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../qt_off/5.3/gcc_64/include/QtGui/qfont.h \
		../qt_off/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../qt_off/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qurl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qurlquery.h \
		../qt_off/5.3/gcc_64/include/QtQuick/QQuickItem \
		../qt_off/5.3/gcc_64/include/QtQuick/qquickitem.h \
		../qt_off/5.3/gcc_64/include/QtQuick/qtquickglobal.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqml.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlprivate.h \
		../qt_off/5.3/gcc_64/include/QtQml/qtqmlglobal.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlparserstatus.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmllist.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmetaobject.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlcomponent.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlerror.h \
		../qt_off/5.3/gcc_64/include/QtQml/qjsvalue.h \
		../qt_off/5.3/gcc_64/include/QtCore/QObject \
		../qt_off/5.3/gcc_64/include/QtCore/QList \
		../qt_off/5.3/gcc_64/include/QtGui/qevent.h \
		../qt_off/5.3/gcc_64/include/QtGui/qregion.h \
		../qt_off/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfile.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qvector2d.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qaccessible.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../qt_off/5.3/gcc_64/include/QtCore/qeventloop.h \
		../qt_off/5.3/gcc_64/include/QtGui/qcolor.h \
		../qt_off/5.3/gcc_64/include/QtGui/qrgb.h \
		highlighter.h \
		../qt_off/5.3/gcc_64/include/QtGui/QSyntaxHighlighter \
		../qt_off/5.3/gcc_64/include/QtGui/qsyntaxhighlighter.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextobject.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextformat.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpen.h \
		../qt_off/5.3/gcc_64/include/QtGui/qbrush.h \
		../qt_off/5.3/gcc_64/include/QtGui/qmatrix.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpolygon.h \
		../qt_off/5.3/gcc_64/include/QtCore/qline.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtransform.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../qt_off/5.3/gcc_64/include/QtGui/qimage.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpixmap.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextoption.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextlayout.h \
		../qt_off/5.3/gcc_64/include/QtGui/qglyphrun.h \
		../qt_off/5.3/gcc_64/include/QtGui/qrawfont.h \
		../qt_off/5.3/gcc_64/include/QtGui/qfontdatabase.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextcursor.h \
		../qt_off/5.3/gcc_64/include/QtCore/QHash \
		../qt_off/5.3/gcc_64/include/QtGui/QTextCharFormat \
		../qt_off/5.3/gcc_64/include/QtCore/QTextCodec \
		../qt_off/5.3/gcc_64/include/QtCore/qtextcodec.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlfile.h \
		documenthandler.h
	/home/kakadu/prog/qt/qt_off/5.3/gcc_64/bin/moc $(DEFINES) -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/mkspecs/linux-g++ -I/home/kakadu/prog/qt/qoq -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/include -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/include/QtQuick -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/include/QtQml -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/include/QtWidgets -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/include/QtNetwork -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/include/QtGui -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/include/QtCore documenthandler.h -o moc_documenthandler.cpp

moc_highlighter.cpp: ../qt_off/5.3/gcc_64/include/QtGui/QSyntaxHighlighter \
		../qt_off/5.3/gcc_64/include/QtGui/qsyntaxhighlighter.h \
		../qt_off/5.3/gcc_64/include/QtCore/qglobal.h \
		../qt_off/5.3/gcc_64/include/QtCore/qconfig.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfeatures.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlogging.h \
		../qt_off/5.3/gcc_64/include/QtCore/qflags.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../qt_off/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../qt_off/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmutex.h \
		../qt_off/5.3/gcc_64/include/QtCore/qnumeric.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobject.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../qt_off/5.3/gcc_64/include/QtCore/qnamespace.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstring.h \
		../qt_off/5.3/gcc_64/include/QtCore/qchar.h \
		../qt_off/5.3/gcc_64/include/QtCore/qbytearray.h \
		../qt_off/5.3/gcc_64/include/QtCore/qrefcount.h \
		../qt_off/5.3/gcc_64/include/QtCore/qarraydata.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlist.h \
		../qt_off/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../qt_off/5.3/gcc_64/include/QtCore/qiterator.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../qt_off/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmetatype.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../qt_off/5.3/gcc_64/include/QtCore/qisenum.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextobject.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextformat.h \
		../qt_off/5.3/gcc_64/include/QtGui/qcolor.h \
		../qt_off/5.3/gcc_64/include/QtGui/qrgb.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringlist.h \
		../qt_off/5.3/gcc_64/include/QtCore/qdatastream.h \
		../qt_off/5.3/gcc_64/include/QtCore/qiodevice.h \
		../qt_off/5.3/gcc_64/include/QtCore/qpair.h \
		../qt_off/5.3/gcc_64/include/QtCore/qregexp.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../qt_off/5.3/gcc_64/include/QtGui/qfont.h \
		../qt_off/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../qt_off/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qshareddata.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qhash.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvector.h \
		../qt_off/5.3/gcc_64/include/QtCore/qpoint.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvariant.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmap.h \
		../qt_off/5.3/gcc_64/include/QtCore/qdebug.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtextstream.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlocale.h \
		../qt_off/5.3/gcc_64/include/QtCore/qset.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpen.h \
		../qt_off/5.3/gcc_64/include/QtGui/qbrush.h \
		../qt_off/5.3/gcc_64/include/QtGui/qmatrix.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpolygon.h \
		../qt_off/5.3/gcc_64/include/QtCore/qrect.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmargins.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsize.h \
		../qt_off/5.3/gcc_64/include/QtGui/qregion.h \
		../qt_off/5.3/gcc_64/include/QtCore/qline.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtransform.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../qt_off/5.3/gcc_64/include/QtGui/qimage.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpixmap.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextoption.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextlayout.h \
		../qt_off/5.3/gcc_64/include/QtGui/qevent.h \
		../qt_off/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../qt_off/5.3/gcc_64/include/QtCore/qurl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qurlquery.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfile.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qvector2d.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qglyphrun.h \
		../qt_off/5.3/gcc_64/include/QtGui/qrawfont.h \
		../qt_off/5.3/gcc_64/include/QtGui/qfontdatabase.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextcursor.h \
		../qt_off/5.3/gcc_64/include/QtCore/QHash \
		../qt_off/5.3/gcc_64/include/QtGui/QTextCharFormat \
		highlighter.h
	/home/kakadu/prog/qt/qt_off/5.3/gcc_64/bin/moc $(DEFINES) -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/mkspecs/linux-g++ -I/home/kakadu/prog/qt/qoq -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/include -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/include/QtQuick -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/include/QtQml -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/include/QtWidgets -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/include/QtNetwork -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/include/QtGui -I/home/kakadu/prog/qt/qt_off/5.3/gcc_64/include/QtCore highlighter.h -o moc_highlighter.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../qt_off/5.3/gcc_64/include/QtWidgets/QApplication \
		../qt_off/5.3/gcc_64/include/QtWidgets/qapplication.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../qt_off/5.3/gcc_64/include/QtCore/qglobal.h \
		../qt_off/5.3/gcc_64/include/QtCore/qconfig.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfeatures.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlogging.h \
		../qt_off/5.3/gcc_64/include/QtCore/qflags.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../qt_off/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../qt_off/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmutex.h \
		../qt_off/5.3/gcc_64/include/QtCore/qnumeric.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstring.h \
		../qt_off/5.3/gcc_64/include/QtCore/qchar.h \
		../qt_off/5.3/gcc_64/include/QtCore/qbytearray.h \
		../qt_off/5.3/gcc_64/include/QtCore/qrefcount.h \
		../qt_off/5.3/gcc_64/include/QtCore/qnamespace.h \
		../qt_off/5.3/gcc_64/include/QtCore/qarraydata.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobject.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlist.h \
		../qt_off/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../qt_off/5.3/gcc_64/include/QtCore/qiterator.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../qt_off/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmetatype.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../qt_off/5.3/gcc_64/include/QtCore/qisenum.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qeventloop.h \
		../qt_off/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../qt_off/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../qt_off/5.3/gcc_64/include/QtCore/qpoint.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsize.h \
		../qt_off/5.3/gcc_64/include/QtGui/qcursor.h \
		../qt_off/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../qt_off/5.3/gcc_64/include/QtWidgets/qwidget.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmargins.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../qt_off/5.3/gcc_64/include/QtCore/qrect.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpalette.h \
		../qt_off/5.3/gcc_64/include/QtGui/qcolor.h \
		../qt_off/5.3/gcc_64/include/QtGui/qrgb.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringlist.h \
		../qt_off/5.3/gcc_64/include/QtCore/qdatastream.h \
		../qt_off/5.3/gcc_64/include/QtCore/qiodevice.h \
		../qt_off/5.3/gcc_64/include/QtCore/qpair.h \
		../qt_off/5.3/gcc_64/include/QtCore/qregexp.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../qt_off/5.3/gcc_64/include/QtGui/qbrush.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvector.h \
		../qt_off/5.3/gcc_64/include/QtGui/qmatrix.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpolygon.h \
		../qt_off/5.3/gcc_64/include/QtGui/qregion.h \
		../qt_off/5.3/gcc_64/include/QtCore/qline.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtransform.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../qt_off/5.3/gcc_64/include/QtGui/qimage.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpixmap.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qshareddata.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qhash.h \
		../qt_off/5.3/gcc_64/include/QtGui/qfont.h \
		../qt_off/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../qt_off/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../qt_off/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../qt_off/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../qt_off/5.3/gcc_64/include/QtGui/qevent.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvariant.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmap.h \
		../qt_off/5.3/gcc_64/include/QtCore/qdebug.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtextstream.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlocale.h \
		../qt_off/5.3/gcc_64/include/QtCore/qset.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../qt_off/5.3/gcc_64/include/QtCore/qurl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qurlquery.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfile.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qvector2d.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qguiapplication.h \
		../qt_off/5.3/gcc_64/include/QtGui/qinputmethod.h \
		../qt_off/5.3/gcc_64/include/QtQml/QQmlApplicationEngine \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlapplicationengine.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlengine.h \
		../qt_off/5.3/gcc_64/include/QtQml/qjsengine.h \
		../qt_off/5.3/gcc_64/include/QtQml/qjsvalue.h \
		../qt_off/5.3/gcc_64/include/QtQml/qtqmlglobal.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlerror.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmldebug.h \
		../qt_off/5.3/gcc_64/include/QtQml/QQmlEngine \
		documenthandler.h \
		../qt_off/5.3/gcc_64/include/QtQuick/QQuickTextDocument \
		../qt_off/5.3/gcc_64/include/QtQuick/qquicktextdocument.h \
		../qt_off/5.3/gcc_64/include/QtGui/QTextDocument \
		../qt_off/5.3/gcc_64/include/QtGui/qtextdocument.h \
		../qt_off/5.3/gcc_64/include/QtQuick/QQuickItem \
		../qt_off/5.3/gcc_64/include/QtQuick/qquickitem.h \
		../qt_off/5.3/gcc_64/include/QtQuick/qtquickglobal.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqml.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlprivate.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlparserstatus.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmllist.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmetaobject.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlcomponent.h \
		../qt_off/5.3/gcc_64/include/QtCore/QObject \
		../qt_off/5.3/gcc_64/include/QtCore/QList \
		../qt_off/5.3/gcc_64/include/QtGui/qaccessible.h \
		highlighter.h \
		../qt_off/5.3/gcc_64/include/QtGui/QSyntaxHighlighter \
		../qt_off/5.3/gcc_64/include/QtGui/qsyntaxhighlighter.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextobject.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextformat.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpen.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextoption.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextlayout.h \
		../qt_off/5.3/gcc_64/include/QtGui/qglyphrun.h \
		../qt_off/5.3/gcc_64/include/QtGui/qrawfont.h \
		../qt_off/5.3/gcc_64/include/QtGui/qfontdatabase.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextcursor.h \
		../qt_off/5.3/gcc_64/include/QtCore/QHash \
		../qt_off/5.3/gcc_64/include/QtGui/QTextCharFormat \
		../qt_off/5.3/gcc_64/include/QtCore/QTextCodec \
		../qt_off/5.3/gcc_64/include/QtCore/qtextcodec.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

documenthandler.o: documenthandler.cpp documenthandler.h \
		../qt_off/5.3/gcc_64/include/QtQuick/QQuickTextDocument \
		../qt_off/5.3/gcc_64/include/QtQuick/qquicktextdocument.h \
		../qt_off/5.3/gcc_64/include/QtGui/QTextDocument \
		../qt_off/5.3/gcc_64/include/QtGui/qtextdocument.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobject.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../qt_off/5.3/gcc_64/include/QtCore/qnamespace.h \
		../qt_off/5.3/gcc_64/include/QtCore/qglobal.h \
		../qt_off/5.3/gcc_64/include/QtCore/qconfig.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfeatures.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlogging.h \
		../qt_off/5.3/gcc_64/include/QtCore/qflags.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../qt_off/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../qt_off/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmutex.h \
		../qt_off/5.3/gcc_64/include/QtCore/qnumeric.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstring.h \
		../qt_off/5.3/gcc_64/include/QtCore/qchar.h \
		../qt_off/5.3/gcc_64/include/QtCore/qbytearray.h \
		../qt_off/5.3/gcc_64/include/QtCore/qrefcount.h \
		../qt_off/5.3/gcc_64/include/QtCore/qarraydata.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlist.h \
		../qt_off/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../qt_off/5.3/gcc_64/include/QtCore/qiterator.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../qt_off/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmetatype.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../qt_off/5.3/gcc_64/include/QtCore/qisenum.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsize.h \
		../qt_off/5.3/gcc_64/include/QtCore/qrect.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmargins.h \
		../qt_off/5.3/gcc_64/include/QtCore/qpoint.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvariant.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmap.h \
		../qt_off/5.3/gcc_64/include/QtCore/qpair.h \
		../qt_off/5.3/gcc_64/include/QtCore/qdebug.h \
		../qt_off/5.3/gcc_64/include/QtCore/qhash.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtextstream.h \
		../qt_off/5.3/gcc_64/include/QtCore/qiodevice.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlocale.h \
		../qt_off/5.3/gcc_64/include/QtCore/qshareddata.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvector.h \
		../qt_off/5.3/gcc_64/include/QtCore/qset.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringlist.h \
		../qt_off/5.3/gcc_64/include/QtCore/qdatastream.h \
		../qt_off/5.3/gcc_64/include/QtCore/qregexp.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../qt_off/5.3/gcc_64/include/QtGui/qfont.h \
		../qt_off/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../qt_off/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qurl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qurlquery.h \
		../qt_off/5.3/gcc_64/include/QtQuick/QQuickItem \
		../qt_off/5.3/gcc_64/include/QtQuick/qquickitem.h \
		../qt_off/5.3/gcc_64/include/QtQuick/qtquickglobal.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqml.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlprivate.h \
		../qt_off/5.3/gcc_64/include/QtQml/qtqmlglobal.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlparserstatus.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmllist.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmetaobject.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlcomponent.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlerror.h \
		../qt_off/5.3/gcc_64/include/QtQml/qjsvalue.h \
		../qt_off/5.3/gcc_64/include/QtCore/QObject \
		../qt_off/5.3/gcc_64/include/QtCore/QList \
		../qt_off/5.3/gcc_64/include/QtGui/qevent.h \
		../qt_off/5.3/gcc_64/include/QtGui/qregion.h \
		../qt_off/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfile.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qvector2d.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qaccessible.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../qt_off/5.3/gcc_64/include/QtCore/qeventloop.h \
		../qt_off/5.3/gcc_64/include/QtGui/qcolor.h \
		../qt_off/5.3/gcc_64/include/QtGui/qrgb.h \
		highlighter.h \
		../qt_off/5.3/gcc_64/include/QtGui/QSyntaxHighlighter \
		../qt_off/5.3/gcc_64/include/QtGui/qsyntaxhighlighter.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextobject.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextformat.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpen.h \
		../qt_off/5.3/gcc_64/include/QtGui/qbrush.h \
		../qt_off/5.3/gcc_64/include/QtGui/qmatrix.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpolygon.h \
		../qt_off/5.3/gcc_64/include/QtCore/qline.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtransform.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../qt_off/5.3/gcc_64/include/QtGui/qimage.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpixmap.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextoption.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextlayout.h \
		../qt_off/5.3/gcc_64/include/QtGui/qglyphrun.h \
		../qt_off/5.3/gcc_64/include/QtGui/qrawfont.h \
		../qt_off/5.3/gcc_64/include/QtGui/qfontdatabase.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextcursor.h \
		../qt_off/5.3/gcc_64/include/QtCore/QHash \
		../qt_off/5.3/gcc_64/include/QtGui/QTextCharFormat \
		../qt_off/5.3/gcc_64/include/QtCore/QTextCodec \
		../qt_off/5.3/gcc_64/include/QtCore/qtextcodec.h \
		../qt_off/5.3/gcc_64/include/QtQml/qqmlfile.h \
		../qt_off/5.3/gcc_64/include/QtGui/QTextCursor \
		../qt_off/5.3/gcc_64/include/QtGui/QFontDatabase \
		../qt_off/5.3/gcc_64/include/QtCore/QFileInfo \
		../qt_off/5.3/gcc_64/include/QtCore/qfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o documenthandler.o documenthandler.cpp

highlighter.o: highlighter.cpp ../qt_off/5.3/gcc_64/include/QtGui/QtGui \
		../qt_off/5.3/gcc_64/include/QtGui/QtGuiDepends \
		../qt_off/5.3/gcc_64/include/QtCore/QtCore \
		../qt_off/5.3/gcc_64/include/QtCore/QtCoreDepends \
		../qt_off/5.3/gcc_64/include/QtCore/qabstractanimation.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobject.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../qt_off/5.3/gcc_64/include/QtCore/qnamespace.h \
		../qt_off/5.3/gcc_64/include/QtCore/qglobal.h \
		../qt_off/5.3/gcc_64/include/QtCore/qconfig.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfeatures.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlogging.h \
		../qt_off/5.3/gcc_64/include/QtCore/qflags.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../qt_off/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../qt_off/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../qt_off/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmutex.h \
		../qt_off/5.3/gcc_64/include/QtCore/qnumeric.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstring.h \
		../qt_off/5.3/gcc_64/include/QtCore/qchar.h \
		../qt_off/5.3/gcc_64/include/QtCore/qbytearray.h \
		../qt_off/5.3/gcc_64/include/QtCore/qrefcount.h \
		../qt_off/5.3/gcc_64/include/QtCore/qarraydata.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlist.h \
		../qt_off/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../qt_off/5.3/gcc_64/include/QtCore/qiterator.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../qt_off/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmetatype.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../qt_off/5.3/gcc_64/include/QtCore/qisenum.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qanimationgroup.h \
		../qt_off/5.3/gcc_64/include/QtCore/qparallelanimationgroup.h \
		../qt_off/5.3/gcc_64/include/QtCore/qpauseanimation.h \
		../qt_off/5.3/gcc_64/include/QtCore/qpropertyanimation.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvariantanimation.h \
		../qt_off/5.3/gcc_64/include/QtCore/qeasingcurve.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvector.h \
		../qt_off/5.3/gcc_64/include/QtCore/qpoint.h \
		../qt_off/5.3/gcc_64/include/QtCore/qvariant.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmap.h \
		../qt_off/5.3/gcc_64/include/QtCore/qpair.h \
		../qt_off/5.3/gcc_64/include/QtCore/qdebug.h \
		../qt_off/5.3/gcc_64/include/QtCore/qhash.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtextstream.h \
		../qt_off/5.3/gcc_64/include/QtCore/qiodevice.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlocale.h \
		../qt_off/5.3/gcc_64/include/QtCore/qshareddata.h \
		../qt_off/5.3/gcc_64/include/QtCore/qset.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringlist.h \
		../qt_off/5.3/gcc_64/include/QtCore/qdatastream.h \
		../qt_off/5.3/gcc_64/include/QtCore/qregexp.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtextcodec.h \
		../qt_off/5.3/gcc_64/include/QtCore/qendian.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlibraryinfo.h \
		../qt_off/5.3/gcc_64/include/QtCore/qdatetime.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qbuffer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qdir.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfileinfo.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfile.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../qt_off/5.3/gcc_64/include/QtCore/qdiriterator.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfileselector.h \
		../qt_off/5.3/gcc_64/include/QtCore/QObject \
		../qt_off/5.3/gcc_64/include/QtCore/QStringList \
		../qt_off/5.3/gcc_64/include/QtCore/qfilesystemwatcher.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlockfile.h \
		../qt_off/5.3/gcc_64/include/QtCore/qloggingcategory.h \
		../qt_off/5.3/gcc_64/include/QtCore/qprocess.h \
		../qt_off/5.3/gcc_64/include/QtCore/qresource.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsavefile.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsettings.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstandardpaths.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtemporarydir.h \
		../qt_off/5.3/gcc_64/include/QtCore/QScopedPointer \
		../qt_off/5.3/gcc_64/include/QtCore/qtemporaryfile.h \
		../qt_off/5.3/gcc_64/include/QtCore/qurl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qurlquery.h \
		../qt_off/5.3/gcc_64/include/QtCore/qabstractitemmodel.h \
		../qt_off/5.3/gcc_64/include/QtCore/qabstractproxymodel.h \
		../qt_off/5.3/gcc_64/include/QtCore/qidentityproxymodel.h \
		../qt_off/5.3/gcc_64/include/QtCore/qitemselectionmodel.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstringlistmodel.h \
		../qt_off/5.3/gcc_64/include/QtCore/qjsonarray.h \
		../qt_off/5.3/gcc_64/include/QtCore/qjsonvalue.h \
		../qt_off/5.3/gcc_64/include/QtCore/qjsondocument.h \
		../qt_off/5.3/gcc_64/include/QtCore/qjsonobject.h \
		../qt_off/5.3/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../qt_off/5.3/gcc_64/include/QtCore/qeventloop.h \
		../qt_off/5.3/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		../qt_off/5.3/gcc_64/include/QtCore/qbasictimer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmath.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmetaobject.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmimedata.h \
		../qt_off/5.3/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		../qt_off/5.3/gcc_64/include/QtCore/qpointer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsharedmemory.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsignalmapper.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsocketnotifier.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsystemsemaphore.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtimer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtranslator.h \
		../qt_off/5.3/gcc_64/include/QtCore/qwineventnotifier.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmimedatabase.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmimetype.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfactoryinterface.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlibrary.h \
		../qt_off/5.3/gcc_64/include/QtCore/qplugin.h \
		../qt_off/5.3/gcc_64/include/QtCore/qpluginloader.h \
		../qt_off/5.3/gcc_64/include/QtCore/quuid.h \
		../qt_off/5.3/gcc_64/include/QtCore/qabstractstate.h \
		../qt_off/5.3/gcc_64/include/QtCore/qabstracttransition.h \
		../qt_off/5.3/gcc_64/include/QtCore/qeventtransition.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfinalstate.h \
		../qt_off/5.3/gcc_64/include/QtCore/qhistorystate.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsignaltransition.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstate.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstatemachine.h \
		../qt_off/5.3/gcc_64/include/QtCore/qexception.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfuture.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfutureinterface.h \
		../qt_off/5.3/gcc_64/include/QtCore/qrunnable.h \
		../qt_off/5.3/gcc_64/include/QtCore/qresultstore.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfuturesynchronizer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qfuturewatcher.h \
		../qt_off/5.3/gcc_64/include/QtCore/qreadwritelock.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsemaphore.h \
		../qt_off/5.3/gcc_64/include/QtCore/qthread.h \
		../qt_off/5.3/gcc_64/include/QtCore/qthreadpool.h \
		../qt_off/5.3/gcc_64/include/QtCore/qthreadstorage.h \
		../qt_off/5.3/gcc_64/include/QtCore/qwaitcondition.h \
		../qt_off/5.3/gcc_64/include/QtCore/qarraydataops.h \
		../qt_off/5.3/gcc_64/include/QtCore/qarraydatapointer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qbitarray.h \
		../qt_off/5.3/gcc_64/include/QtCore/qbytearraymatcher.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcache.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcollator.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcommandlineoption.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcommandlineparser.h \
		../qt_off/5.3/gcc_64/include/QtCore/qcryptographichash.h \
		../qt_off/5.3/gcc_64/include/QtCore/qelapsedtimer.h \
		../qt_off/5.3/gcc_64/include/QtCore/qline.h \
		../qt_off/5.3/gcc_64/include/QtCore/qlinkedlist.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmargins.h \
		../qt_off/5.3/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		../qt_off/5.3/gcc_64/include/QtCore/qqueue.h \
		../qt_off/5.3/gcc_64/include/QtCore/qrect.h \
		../qt_off/5.3/gcc_64/include/QtCore/qsize.h \
		../qt_off/5.3/gcc_64/include/QtCore/qregularexpression.h \
		../qt_off/5.3/gcc_64/include/QtCore/qscopedvaluerollback.h \
		../qt_off/5.3/gcc_64/include/QtCore/qstack.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtextboundaryfinder.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtimeline.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtimezone.h \
		../qt_off/5.3/gcc_64/include/QtCore/qxmlstream.h \
		../qt_off/5.3/gcc_64/include/QtCore/qtcoreversion.h \
		../qt_off/5.3/gcc_64/include/QtGui/qaccessible.h \
		../qt_off/5.3/gcc_64/include/QtGui/qcolor.h \
		../qt_off/5.3/gcc_64/include/QtGui/qrgb.h \
		../qt_off/5.3/gcc_64/include/QtGui/qevent.h \
		../qt_off/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../qt_off/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../qt_off/5.3/gcc_64/include/QtGui/qregion.h \
		../qt_off/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../qt_off/5.3/gcc_64/include/QtGui/qvector2d.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qaccessiblebridge.h \
		../qt_off/5.3/gcc_64/include/QtGui/qaccessibleobject.h \
		../qt_off/5.3/gcc_64/include/QtGui/qaccessibleplugin.h \
		../qt_off/5.3/gcc_64/include/QtGui/qbitmap.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpixmap.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qimage.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtransform.h \
		../qt_off/5.3/gcc_64/include/QtGui/qmatrix.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpolygon.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../qt_off/5.3/gcc_64/include/QtGui/qicon.h \
		../qt_off/5.3/gcc_64/include/QtGui/qiconengine.h \
		../qt_off/5.3/gcc_64/include/QtGui/qiconengineplugin.h \
		../qt_off/5.3/gcc_64/include/QtGui/qimageiohandler.h \
		../qt_off/5.3/gcc_64/include/QtGui/qimagereader.h \
		../qt_off/5.3/gcc_64/include/QtGui/qimagewriter.h \
		../qt_off/5.3/gcc_64/include/QtGui/qmovie.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpicture.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpictureformatplugin.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpixmapcache.h \
		../qt_off/5.3/gcc_64/include/QtGui/qstandarditemmodel.h \
		../qt_off/5.3/gcc_64/include/QtGui/qbrush.h \
		../qt_off/5.3/gcc_64/include/QtGui/qfont.h \
		../qt_off/5.3/gcc_64/include/QtGui/qclipboard.h \
		../qt_off/5.3/gcc_64/include/QtGui/qcursor.h \
		../qt_off/5.3/gcc_64/include/QtGui/qdrag.h \
		../qt_off/5.3/gcc_64/include/QtGui/qgenericplugin.h \
		../qt_off/5.3/gcc_64/include/QtGui/qgenericpluginfactory.h \
		../qt_off/5.3/gcc_64/include/QtGui/qguiapplication.h \
		../qt_off/5.3/gcc_64/include/QtGui/qinputmethod.h \
		../qt_off/5.3/gcc_64/include/QtGui/qoffscreensurface.h \
		../qt_off/5.3/gcc_64/include/QtGui/qsurface.h \
		../qt_off/5.3/gcc_64/include/QtGui/qsurfaceformat.h \
		../qt_off/5.3/gcc_64/include/QtGui/qopenglcontext.h \
		../qt_off/5.3/gcc_64/include/QtGui/QSurfaceFormat \
		../qt_off/5.3/gcc_64/include/QtGui/qopengl.h \
		../qt_off/5.3/gcc_64/include/QtCore/qt_windows.h \
		../qt_off/5.3/gcc_64/include/QtGui/qopengles2ext.h \
		../qt_off/5.3/gcc_64/include/QtGui/qopenglext.h \
		../qt_off/5.3/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpalette.h \
		../qt_off/5.3/gcc_64/include/QtGui/qscreen.h \
		../qt_off/5.3/gcc_64/include/QtCore/QList \
		../qt_off/5.3/gcc_64/include/QtCore/QRect \
		../qt_off/5.3/gcc_64/include/QtCore/QSize \
		../qt_off/5.3/gcc_64/include/QtCore/QSizeF \
		../qt_off/5.3/gcc_64/include/QtGui/QTransform \
		../qt_off/5.3/gcc_64/include/QtGui/qsessionmanager.h \
		../qt_off/5.3/gcc_64/include/QtGui/qstylehints.h \
		../qt_off/5.3/gcc_64/include/QtGui/qwindow.h \
		../qt_off/5.3/gcc_64/include/QtCore/QEvent \
		../qt_off/5.3/gcc_64/include/QtCore/QMargins \
		../qt_off/5.3/gcc_64/include/QtGui/qgenericmatrix.h \
		../qt_off/5.3/gcc_64/include/QtGui/qmatrix4x4.h \
		../qt_off/5.3/gcc_64/include/QtGui/qvector3d.h \
		../qt_off/5.3/gcc_64/include/QtGui/qvector4d.h \
		../qt_off/5.3/gcc_64/include/QtGui/qquaternion.h \
		../qt_off/5.3/gcc_64/include/QtGui/qopenglbuffer.h \
		../qt_off/5.3/gcc_64/include/QtGui/qopengldebug.h \
		../qt_off/5.3/gcc_64/include/QtGui/qopenglframebufferobject.h \
		../qt_off/5.3/gcc_64/include/QtGui/qopenglfunctions.h \
		../qt_off/5.3/gcc_64/include/QtGui/qopenglpaintdevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qopenglpixeltransferoptions.h \
		../qt_off/5.3/gcc_64/include/QtCore/QSharedDataPointer \
		../qt_off/5.3/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../qt_off/5.3/gcc_64/include/QtGui/qopengltexture.h \
		../qt_off/5.3/gcc_64/include/QtGui/qopengltimerquery.h \
		../qt_off/5.3/gcc_64/include/QtGui/qopenglvertexarrayobject.h \
		../qt_off/5.3/gcc_64/include/QtGui/qbackingstore.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpagedpaintdevice.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpagelayout.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpagesize.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpaintengine.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpainter.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextoption.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpen.h \
		../qt_off/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../qt_off/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../qt_off/5.3/gcc_64/include/QtGui/qpdfwriter.h \
		../qt_off/5.3/gcc_64/include/QtGui/qabstracttextdocumentlayout.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextlayout.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextformat.h \
		../qt_off/5.3/gcc_64/include/QtGui/qglyphrun.h \
		../qt_off/5.3/gcc_64/include/QtGui/qrawfont.h \
		../qt_off/5.3/gcc_64/include/QtGui/qfontdatabase.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextcursor.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextdocument.h \
		../qt_off/5.3/gcc_64/include/QtGui/qstatictext.h \
		../qt_off/5.3/gcc_64/include/QtGui/qsyntaxhighlighter.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextobject.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextdocumentfragment.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextdocumentwriter.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtextlist.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtexttable.h \
		../qt_off/5.3/gcc_64/include/QtGui/qdesktopservices.h \
		../qt_off/5.3/gcc_64/include/QtGui/qvalidator.h \
		../qt_off/5.3/gcc_64/include/QtGui/qtguiversion.h \
		highlighter.h \
		../qt_off/5.3/gcc_64/include/QtGui/QSyntaxHighlighter \
		../qt_off/5.3/gcc_64/include/QtCore/QHash \
		../qt_off/5.3/gcc_64/include/QtGui/QTextCharFormat
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o highlighter.o highlighter.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_documenthandler.o: moc_documenthandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_documenthandler.o moc_documenthandler.cpp

moc_highlighter.o: moc_highlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_highlighter.o moc_highlighter.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/qoq/bin || mkdir -p $(INSTALL_ROOT)/opt/qoq/bin
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/qoq/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/qoq/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/qoq/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

